Add optional variable `public` to routes to ignore `site.allowlist`
simplificator/ansible-role-caddy pull request #17
Opened 2024-01-11 14:29 UTC by tomcbe

There are cases where most of the routes should only be allowed for the IP addresses defined in `allowlist`, but certain routes should be available publicly.

2024-01-11 14:42 UTC, tomcbe commented
Sorry, I just realised the template is not yet working. I'll give an update, once I fixed the issues and the PR is actually ready for a review.

2024-01-11 15:31 UTC, tomcbe commented
Would now be ready for a review.

2024-01-12 11:44 UTC, andyundso requested changes
I would appreciate if you can extend the `reverse-proxy` Molecule testing scenario. I imagine:

* in `molecule/reverse-proxy/converge.yml`, add an additional entry to `caddy_sites` like `mixed.example.com`, one route will use an allowlist and the other one will be public.
* Run `molecule create && molecule converge`
* Copy the generated Caddyfile from the Molecule container (using `molecule login`, the Caddyfile is at `/etc/caddy/Caddyfile`) to `molecule/reverse-proxy/files/Caddyfile.expected`.

2024-01-12 12:45 UTC, tomcbe commented
> I would appreciate if you can extend the `reverse-proxy` Molecule testing scenario. I imagine:

Sure, I'll do that.

2024-01-12 13:09 UTC, tomcbe commented
As just discussed on slack: I'll change the name of the new variable to `ignore_allow_list` as suggested by @docuteam-kun.

2024-01-12 18:38 UTC, andyundso approved these changes
perfect, thank you very much!

2024-01-12 18:38 UTC, merged