Adding configuration elements to block based on user-agents
simplificator/ansible-role-caddy pull request #20
Opened 2024-09-05 15:40 UTC by robin-francois

With the increase of traffic generated by generative AI robots, and since those bots do not respect the robots.txt, user-agent filtering seems at the moment a good approach to prevent services being overloaded.

This PR adds a new variable to configure a block list of user agents. This list is case sensitive.

2024-09-09 10:28 UTC, tomcbe requested changes
Hi @robin-francois

I reviewed th PR for docuteam: I have a few smaller suggestions, but in general it looks good to me.

2024-09-09 10:28 UTC, tomcbe commented on templates/Caddyfile.j2
> +  {% if site.useragent_blocklist is defined %}
Use `{%-` to remove the newline before `@badbots {`

2024-09-09 10:28 UTC, tomcbe commented on templates/Caddyfile.j2
> +  {% endif %}
Use `-%}` to remove the extra newline.

2024-09-09 10:28 UTC, tomcbe commented on templates/Caddyfile.j2
> +    {% for ua in site.useragent_blocklist %}
Use `{%-` to remove the extra newline

2024-09-09 10:28 UTC, tomcbe commented on templates/Caddyfile.j2
> +    {% endfor %}
Use `{%-` to remove the extra newline

2024-09-09 16:11 UTC, robin-francois commented on templates/Caddyfile.j2
> +    abort
Well, I would say that if they were respecting us, we could be respecting them. But there are not. We want to be sure that they do not come back and do not try again.

2024-09-11 12:18 UTC, robin-francois commented
Apart from the response to send, I think all points have been solved.

2024-09-12 15:38 UTC, tomcbe commented on templates/Caddyfile.j2
> +    abort
Artefactual sends `403` status code by default in their Nginx Role for AtoM:

https://github.com/artefactual-labs/ansible-nginx/blob/master/defaults/main/main.yml#L70

I still wonder, if sending is better than no answer.

2024-09-12 15:51 UTC, tomcbe reviewed
Apart form the discussion about wether to send a 403 HTTP status code or aborting the connection, this PR looks good to me now.

2024-09-13 09:10 UTC, robin-francois commented
We can easily reply 403 if you prefer. I will just need to double check how to do it.

2024-09-13 09:48 UTC, robin-francois commented
@tomcbe I have tested how to reply a 403 with some simple HTML content. I have made a new commit to do 403 instead of closing the TCP connection.

2024-09-13 13:58 UTC, tomcbe approved these changes

2024-09-13 14:01 UTC, tomcbe commented
@robin-francois I approved your PR now, but as this is a repository managed by simplificator. I can't merge it.
I'll create a PR for our provisioning projects to use your fork of the role in the meantime.

@cedricwider @tizpuppi Can one of you review this PR and merge it if agree with the proposed changes?

2024-09-25 15:53 UTC, tomcbe approved these changes

2024-10-21 10:03 UTC, cedricwider approved these changes

2024-10-21 11:52 UTC, cedricwider commented
Closing this PR in favor of #22

2024-10-21 11:52 UTC, closed without merging